# Generated by Django 5.2.12 on 2026-03-11 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_alm', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_alm', models.CharField(max_length=80)),
                ('direccion_alm', models.CharField(blank=True, max_length=250, null=True)),
                ('ciudad_alm', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_alm', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'almacen',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(max_length=80, unique=True)),
                ('descripcion_cat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_brand', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_brand', models.CharField(max_length=80, unique=True)),
                ('sitio_web_brand', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre_prod', models.CharField(max_length=120)),
                ('descripcion_prod', models.TextField(blank=True, null=True)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.marca')),
                ('id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventario.categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('id_alm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.almacen')),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='inventario.producto')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
